### ISSUE TITLE
Consider if page loading for large complex sites can be improved

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/token_help#7]
With entity_token enabled, the token help report can be very slow to load
![OuYZi9iXPR](https://user-images.githubusercontent.com/20357797/183627666-b0e257c8-6ebb-4bf6-9f69-f181344d8d8d.gif)

The page was 16.24MB and took 3.37 minutes to load completely and that is for a site running in Lando.
I wonder if it would be possible to break it up or just load the top level first and load the sub-levels with Jquery? A kind of lazy loading?

**Comment by bugfolder** [comment]
Completely agree with the issue being a problem. This module just calls the system function `theme('token_tree', ...)` to render the token browser, though, so I think the solution would lie in making the suggested change to core; the same issue would presumably arise anywhere the token browser is being rendered with `'token_types' => 'all'`.

**Comment by yorkshire-pudding** [comment]
@bugfolder - I'm going to attempt to port Fast Token Browser - see https://github.com/backdrop-ops/contrib/issues/664 - if this uses core functions then it might sort it.

**Comment by yorkshire-pudding** [comment]
My testing so far suggests that fast token browser will solve the issue.

**Comment by yorkshire-pudding** [comment]
Now released - https://github.com/backdrop-contrib/fast_token_browser

**Comment by bugfolder** [comment]
I'll reopen this as a reminder to me to (a) try it out, and (b) add a note about it to the README file for this module ("If you have Entity Token enabled and the page won't load or takes forever, try Fast Token Browser").

Maybe FTB should be a candidate for core, too.
